[package]
name = "autoresponsebot"
version = "0.1.0"
authors = ["Ross Nomann <rossnomann@protonmail.com>"]

[dependencies]
dotenv = "0.12"
rand = "0.5"
ratelimit_meter = "2.0.0"
regex = "1.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
teleborg = "0.1"
